text1 = ["What were the main key points or takeaways from today's lecture?",
        "Can you summarize the lecture in your own words?",
        "Were there any concepts or ideas discussed in the lecture that you found challenging or unclear? If so, please explain.",
        "How do you think the material covered in this lecture relates to previous lectures or topics we've discussed in the course?",
        "Can you provide an example or real-life application of one of the concepts discussed in the lecture?",
        "Did the lecturer mention any open questions or areas of research related to the topic? What are your thoughts on those?",
        "How would you apply what you've learned in today's lecture to solve a specific problem or scenario?",
        "Were there any interesting or surprising insights from the lecture that you'd like to share or discuss further?",
        "Can you identify any connections between the content of this lecture and current events or trends in the field?",
        "Do you have any questions or concerns about the material that was covered today?"]

text2 = ["Was the speed of the session and time management of the professor reasonable?",
        "Were relevant course materials provided to follow up the course?",
        "Were recommended textbooks, websites and research papers related to the topic provided during the lectures?",
        "Was the syllabus properly covered in the class?",
        "Feel free to let me know the number of worked examples and tutorials adequate during the lectures?",
        "Can you tell me about how the professor encourage self studies by the student?",
        "This is an important question, were the practical applications relevant to the module discussed during the lecture?",
        "Can you comment about the professional approach of the professor?",
        "Were proper instructions given regarding the evaluation of the module during the lectures?",
        "Can you comment on help of continuous assessments in the learning process?",
        "Were the feedbacks on continuous assessments helpful to indentify your weakness before the final examination?"]

text3 = ["To what extent did the lecturer facilitate and encourage active discussions among students?", 
         "How effective was the lecturer in creating an environment conducive to student participation?",
         "How frequently did the lecturer recognize and appreciate student responses?", 
         "How well did the lecturer manage the balance between encouraging participation and maintaining order?",
         "How actively did the lecturer encourage students to ask questions?", 
         "How constructive and helpful was the feedback given to students during discussions?",
         "How well did the lecturer adapt their teaching based on student responses?", 
         "What strategies did the lecturer employ to enhance student engagement during discussions?",
         "How effective were these strategies in promoting a dynamic and engaging learning environment?", 
         "How accessible and approachable did the lecturer appear during interactions with students?",
         "How did the lecturer balance individual and group interactions for good learning experience?"]

text4 = ["Was the pace of the delivery consistent throughout the session?", 
         "Did the lecturer maintain an appropriate speed, allowing for easy understanding?",
         "How effective were the black/white board or PowerPoint presentations in conveying information?", 
         "Could you easily hear and understand the lecturer throughout the session?",
         "How clear were the verbal explanations provided by the lecturer?", 
         "Were complex concepts articulated in a way that was easy to comprehend?",
         "How effectively did the lecturer address questions to ensure understanding?", 
         "How responsive was the lecturer to feedback provided by students?",
         "How well did the lecturer accommodate diverse learning preferences?"]